### ISSUE TITLE
Iteration Plan for March 2019

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1690]
This plan captures our work in **March**.

## Expected Updates

- [x] March 7, 2019: `vscode` v1.32 #1688 #1713 c29202e #1733
- [x] March 12, 2019: Patch Tuesday for Microsoft #1728
- [x] March 25, 2019: `python-3` v3.7.3 [Schedule](https://www.python.org/dev/peps/pep-0537/#id3) #1755
- [ ] March 28, 2019: `typescript` v3.4 Microsoft/TypeScript#30281 [TypeScript 3.4.1](https://github.com/Microsoft/TypeScript/releases/tag/v3.4.1)

## New Packages

- [ ] `dotnet-runtime`
  - [ ] Armv8-A 64-bit (AArch64)
  - [ ] Armv7-A
- [ ] `dotnet-sdk`
  - [ ] Armv8-A 64-bit (AArch64)
  - [ ] Armv7-A
- [ ] `powershell`
  - [ ] Armv8-A 64-bit (AArch64)
  - [ ] Armv7-A

## Documentation

- [ ] Package Support Policy
  - [x] Lifecycle Policy #1747
    - [x] How does channels from upstream match with ours?
    - [ ] What kind of support is provided for those packages?

**Comment by KexyBiscuit** [comment]
Will we stay on LTS for OpenJDK? @liushuyu

**Comment by MingcongBai** [comment]
In accordance to our update policies (documentation pending), yes, we *should* stay on LTS.

**Comment by KexyBiscuit** [comment]
Moving to [April](https://github.com/AOSC-Dev/aosc-os-abbs/issues/1762).
