### ISSUE TITLE
Iteration Plan for May 2019

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1830]
This plan captures our work in **May**. `testing` branch has been freezed, so major upgrade happens on `explosive` only.

## Expected updates

- [ ] May 14, 2019: Patch Tuesday for Microsoft [Security Update Guide](https://portal.msrc.microsoft.com/en-us/security-guidance)
- [ ] May 17, 2019: `vscode` v1.34.0 Microsoft/vscode#73175 [1.34.0](https://github.com/microsoft/vscode/releases/tag/1.34.0)
- [ ] May 31, 2019: `vscode` v1.35.0 Microsoft/vscode#74143

## Released updates

- [ ] April 2, 2019: KDE Plasma v5.15.4 [Schedules/Plasma 5](https://community.kde.org/Schedules/Plasma_5)
- [ ] :hand: April 9, 2019: Patch Tuesday for Microsoft [Security Update Guide](https://portal.msrc.microsoft.com/en-us/security-guidance)
  - [ ] .NET Core 2.1 v2.1.10 SDK v2.1.603 Runtime v2.1.10 [Release notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.10/2.1.10.md)
  - [ ] .NET Core 2.2 v2.2.4 SDK v2.2.203 Runtime v2.2.4 [Release notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.4/2.2.4.md)
- [ ] April 13, 2019: `plasma-framework` v5.57 [Schedules/Frameworks](https://community.kde.org/Schedules/Frameworks)
- [ ] April 15, 2019: `libreoffice` v6.2.3 [Release Plan 6.2](https://wiki.documentfoundation.org/ReleasePlan/6.2)
- [ ] April 29, 2019: `libreoffice` v6.1.6 [Release Plan 6.1](https://wiki.documentfoundation.org/ReleasePlan/6.1)
- ~May 2, 2019: `pgadmin` v4.6 [Version 4.6](https://www.pgadmin.org/docs/pgadmin4/dev/release_notes_4_6.html)~
- [ ] May 9, 2019: `postgresql` v10.8 [Notes](https://www.postgresql.org/docs/10/release-10-8.html) #1833
- [ ] May 9, 2019: `postgresql` v11.3 [Notes](https://www.postgresql.org/docs/11/release-11-3.html) #1833
- ~May 30, 2019: `pgadmin` v4.7 [Version 4.7](https://www.pgadmin.org/docs/pgadmin4/dev/release_notes_4_7.html)~
- [ ] June 3, 2019: `pgadmin` v4.8 [Version 4.8](https://www.pgadmin.org/docs/pgadmin4/dev/release_notes_4_8.html)

## Documentation

- [ ] Lifecycle Policy
- [ ] [Security updates for 2019](https://aosc.wiki/aosa/archive/2019)

## Deferred items

- March 13, 2019: GNOME v3.32 [GNOME 3.32 Released](https://www.gnome.org/news/2019/03/gnome-3-32-released/)
- March 18, 2019: MATE v1.22 [
MATE 1.22 released](https://mate-desktop.org/blog/2019-03-18-mate-1-22-released/)
- April 18, 2019: KDE Applications v19.04 [Schedules/Applications/19.04 Release Schedule](https://community.kde.org/Schedules/Applications/19.04_Release_Schedule)
- May 29, 2019: TypeScript v3.5 [typescript](https://www.npmjs.com/package/typescript/v/3.5.1)

## See also

- [2018 冬季周期工作指南 / Season Cycle Winter 2018](https://gist.github.com/MingcongBai/78f6923828bccc51f81019fd99462e6a)
  - I know, it's already summer in the Northern Hemisphere... Let's pretend we're in the opposite side of Earth.

**Comment by KexyBiscuit** [comment]
Moving to [June](https://github.com/AOSC-Dev/aosc-os-abbs/issues/1870).
