### ISSUE TITLE
Iteration Plan for June 2019

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1870]
This plan captures our work in **June**. Work items are being processed slowly, please be patient, thank you.

## Expected updates

- [x] June 6, 2019: `vscode` v1.35.0 Microsoft/vscode#74412 [1.35.0](https://github.com/microsoft/vscode/releases/tag/1.35.0) https://github.com/AOSC-Dev/aosc-os-abbs/commit/97406479bade49f2f7c2218d50f6b8e976c4c81c
- [ ] June 11, 2019: Patch Tuesday for Microsoft [Security Update Guide](https://portal.msrc.microsoft.com/en-us/security-guidance)
- [x] June 11, 2019: `vscode` v1.35.1 Microsoft/vscode#75285 [1.35.1](https://github.com/microsoft/vscode/releases/tag/1.35.1) https://github.com/AOSC-Dev/aosc-os-abbs/commit/9ab85db3015bf6ad7c17b8f7a02877fbcee264c2

## Released updates

- [ ] May 7, 2019: KDE Plasma v5.15.5 [Plasma 5.15.5](https://kde.org/announcements/plasma-5.15.5.php)
- [ ] May 7, 2019: `libreoffice` v6.1.6 [Release of LibreOffice 6.1.6](https://blog.documentfoundation.org/blog/2019/05/07/libreoffice-616/)
- [ ] May 22, 2019: `libreoffice` v6.2.4 [The Document Foundation releases LibreOffice 6.2.4](https://blog.documentfoundation.org/blog/2019/05/22/tdf-releases-libreoffice-6-2-4/)
- ~June 3, 2019: `pgadmin` v4.8 [Version 4.8](https://www.pgadmin.org/docs/pgadmin4/dev/release_notes_4_8.html)~
- [ ] June 20, 2019: `postgresql` v10.9 [Release 10.9](https://www.postgresql.org/docs/10/release-10-9.html) #1869
- [ ] June 20, 2019: `postgresql` v11.4 [Release 11.4](https://www.postgresql.org/docs/11/release-11-4.html) #1869
- [ ] June 27, 2019: `pgadmin` v4.9 [Version 4.9](https://www.pgadmin.org/docs/pgadmin4/dev/release_notes_4_9.html)

## Documentation

- [ ] Lifecycle Policy
- [ ] [Security updates for 2019](https://aosc.wiki/aosa/archive/2019)

## Deferred items

- March 13, 2019: GNOME v3.32 [GNOME 3.32 Released](https://www.gnome.org/news/2019/03/gnome-3-32-released/)
- March 18, 2019: MATE v1.22 [MATE 1.22 released](https://mate-desktop.org/blog/2019-03-18-mate-1-22-released/)
- June 6, 2019: KDE Applications v19.04.2 [Applications 19.04.2](https://kde.org/announcements/announce-applications-19.04.2.php)
- June 8, 2019: `plasma-framework` v5.59.0 [KDE Frameworks 5.59.0](https://kde.org/announcements/kde-frameworks-5.59.0.php)
- June 13, 2019: TypeScript v3.5.2 [typescript](https://www.npmjs.com/package/typescript/v/3.5.2)
- June 18, 2019: KDE Plasma v5.16.1 [Plasma 5.16.1](https://kde.org/announcements/plasma-5.16.1.php)

## See also

- [2018 冬季周期工作指南 / Season Cycle Winter 2018](https://gist.github.com/MingcongBai/78f6923828bccc51f81019fd99462e6a)

**Comment by KexyBiscuit** [comment]
Moving to [Summer](https://github.com/AOSC-Dev/aosc-os-abbs/issues/1896).
