### ISSUE TITLE
PowerPC 32/64 Big Endian TODO

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#2108]
Listed below are tasks to be addressed for the `powerpc` (`ppc32be`) and `ppc64` (`ppc64be`) ports:

- [x] Synchronise package versions to mitigate dependency issues. #2106
- [x] Transition to GRUB as the default bootloader. #2107
- [x] Transition to Retro, RFC pending.

This issue will also serve as a concentrated location for discussions and troubleshooting given the poor maintenance statuses for both ports.

**Comment by EchedelleLR** [comment]
> Desktop-enabled distributions will use (at least) IceWM, and (at most) XFCE.

I reply to this part of the post referenced in the other issue (#2106). I use to be a "mouse enthusiast" and since 9wm and w9wm are not upgraded but "finished" I would want to know if there is no issue to be added. The only fact is that, at least, w9wm needs a three button mouse where, at least, old powermac only included a 2 button mouse by default (anyways you can change it).

Edited by @MingcongBai : Added issue reference.

**Comment by MingcongBai** [comment]
Sure thing, this package can be introduced to the repository. My reasoning behind IceWM is its relatively complete FD.o compliance (.desktop support, icon theme support, etc.), graphical settings, and localisation support.

**Comment by EchedelleLR** [comment]
Yes, I have used IceWM in a limited resources machine for a while. I am also glad that it's included.

**Comment by MingcongBai** [comment]
> Yes, I have used IceWM in a limited resources machine for a while. I am also glad that it's included.

And I brought it up as the fact that we need a default for the Retro distributions, but frankly I still need to look into it more since I'm still in the warm beds of Plasma Desktop.

Otherwise, I should be working on an RFC document for AOSC OS/Retro in the near future.

**Comment by EchedeyLR** [comment]
Sorry but I have to ask here: information for recursive umount after finishing the installation before rebooting the machine?

**Comment by MingcongBai** [comment]
`umount -lf /path/to/mountpoint` should do.

**Comment by EchedeyLR** [comment]
I tried with -R saying me that the system was busy a lot of times, I even checked with lsof as suggested saying systemd services running. I got a bit stressed and tried to shutdown normally expecting the filesystem to be unmounted as expected. 9 minutes later I lost the patient waiting with the black screen and the cursor and forced shutdown. I must start the installation again.

**Comment by EchedeyLR** [comment]
Sorry but as far I have not touched so much with bash loops "# for i in dev proc sys; do mount --rbind /$i /mnt/$i; done" get me confused to umount later

So, I should do umount -lf to /mnt/sys, umount -lf to /mnt/proc and finally to /mnt/dev

Is this correct?

**Comment by MingcongBai** [comment]
We are now keeping these ports as Retro ports, and they are now using GRUB. Closing.
